name: Deploy Backend to Azure Web App (PROD)

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - '.github/workflows/azure-backend-deploy_prod.yml'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'cloudsynk-backend-api-prod'  
  NODE_VERSION: '22.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: |
        cd server
        npm ci --production

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
        package: ./server
